# Generated by Django 3.1.1 on 2020-11-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('symbol', models.CharField(max_length=5)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
    ]
